# name: Hetzner cloud pipeline

# on:
#   workflow_dispatch:
#   push:
#     branches: [main]
#     paths: ["hetzner/**"]

#   pull_request:
#     branches: [main, dev, feat/**]
#     paths: ["hetzner/**"]
    
# permissions:
#   contents: read
#   issues: write

# jobs:
#   plan:
#     name: Terraform plan
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}            
#       - name: Terraform setup
#         uses: hashicorp/setup-terraform@v3
#       - name: Terraform init
#         working-directory: ./hetzner
#         run: terraform init
#       - name: Terraform plan
#         working-directory: ./hetzner
#         env:
#           TF_VAR_hetzner_token: ${{ secrets.HETZNER_TOKEN }}
#           TF_VAR_ssh_port: ${{ secrets.SSH_PORT }}
#           TF_VAR_user_manager: ${{ secrets.USER_MANAGER }}
#           TF_VAR_user_manager_password: ${{ secrets.USER_MANAGER_PASSWORD }}
#           TF_VAR_user_manager_ssh_pub: ${{ secrets.USER_MANAGER_SSH_PUB }}
#           TF_VAR_user_manager_ssh_key: ${{ secrets.USER_MANAGER_SSH_KEY }}
#           TF_VAR_user_deploy: ${{ secrets.USER_DEPLOY }}
#           TF_VAR_user_deploy_password: ${{ secrets.USER_DEPLOY_PASSWORD }}
#           TF_VAR_user_deploy_ssh_pub: ${{ secrets.USER_DEPLOY_SSH_PUB }}
#           TF_VAR_user_deploy_ssh_key: ${{ secrets.USER_DEPLOY_SSH_KEY }}
#         run: terraform plan -out terraform.plan    
#       - name: Upload artifact
#         uses: actions/upload-artifact@master
#         with:
#           name: terraform-plan
#           path: hetzner/terraform.plan

#   deploy:
#     name: Terraform Deploy
#     needs: plan
#     if: github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}
#       - name: Terraform setup
#         uses: hashicorp/setup-terraform@v3
#       - name: Terraform init
#         working-directory: ./hetzner
#         run: terraform init              
#       - name: Download artifact
#         uses: actions/download-artifact@master
#         with:
#           name: terraform-plan
#           path: hetzner/terraform.plan         
#       - name: Deploy terraform
#         working-directory: ./hetzner
#         env:
#           TF_VAR_hetzner_token: ${{ secrets.HETZNER_TOKEN }}
#           TF_VAR_ssh_port: ${{ secrets.SSH_PORT }}
#           TF_VAR_user_manager: ${{ secrets.USER_MANAGER }}
#           TF_VAR_user_manager_password: ${{ secrets.USER_MANAGER_PASSWORD }}
#           TF_VAR_user_manager_ssh_pub: ${{ secrets.USER_MANAGER_SSH_PUB }}
#           TF_VAR_user_manager_ssh_key: ${{ secrets.USER_MANAGER_SSH_KEY }}
#           TF_VAR_user_deploy: ${{ secrets.USER_DEPLOY }}
#           TF_VAR_user_deploy_password: ${{ secrets.USER_DEPLOY_PASSWORD }}
#           TF_VAR_user_deploy_ssh_pub: ${{ secrets.USER_DEPLOY_SSH_PUB }}
#           TF_VAR_user_deploy_ssh_key: ${{ secrets.USER_DEPLOY_SSH_KEY }}
#         run: |
#           terraform apply --auto-approve=true
